#pragma once
#include <iostream>
#include <vector>
#include <cstdlib>
#include <algorithm>
#include <SFML/Graphics.hpp>
#include <SFML/System.hpp>
#include <SFML/Window.hpp>
#include <random>
#include <assert.h>
#include <windows.h>
